### ISSUE TITLE
Still High rent and terrain color overview

### ISSUE THREAD

**Issue by SimBoRRis** [Jimmyokok/LandValueOverhaul#15]
Frist of all, I want to say that this is an essential mod for cs2, no one should play without it. I used it before pdx mods and it was flawless, as soon as I saw it today published, I subscribed and wanted to start playing cs2 again. 
But this version is different (game version is different as well), I loaded a city which I build with previous version of Land Value Overhaul and almost immediately High Rent complaints everywhere (last time I played, there wasn't even a single High Rent complain). 
Also when you are in land value info mod, fertile land, telecom covarage, air and noise pollution, there is no color on the ground. I tested this whit only Land Value Overhaul mod, every other mod disabled.

**Comment by Jimmyokok** [comment]
Go to the LandValueOverhual.log and see if building upkeep get modified, if not, it's not correctly loaded, and it is due to PDXMods bugs.

The land value info is just not there for modded saves from previous versions, no matter with or without any mod.

**Comment by SimBoRRis** [comment]
Did you updated the mod, or did pdx finally loaded as it should? I loaded up a game now, some old city with a lot High Rent issues, they all disappeared in a min. Unfortunately in info those info panels, there is still no color on the ground.

**Comment by Jimmyokok** [comment]
If you switch from BepInEx to PMODs, you need to remove EVERYTHING related to it. And I don't know if they can be used simutaneously, since I have experienced weird mod loading behaviors using both.

**Comment by SimBoRRis** [comment]
> If you switch from BepInEx to PMODs, you need to remove EVERYTHING related to it. And I don't know if they can be used simultaneously, since I have experienced weird mod loading behaviors using both.

Yes, on 25th March I reinstalled the game and removed all leftover folders.

**Comment by Jimmyokok** [comment]
If the high rent issue disappeared quickly, then it should'nt be a problem.

The LV info panel just won't show up. I have tried a 1.0.19f1 save on 1.1.0f1, without ANY mod, and also no color on the ground.

**Comment by Jimmyokok** [comment]
The new modded LV mechanism is indeed slightly different from 1.4.3, and it need more testing. 

If at your convenience, could you report what kind of zones tend to yield high-rent warnings. If it's the low-density residentials, what is the average rent and maximum rent (via the developer mode)?

**Comment by SimBoRRis** [comment]
I was talking about this info view
With LVO
-Natural Resourses
![Natural Resourses LV](https://github.com/Jimmyokok/LandValueOverhaul/assets/165592666/60405497-1ec0-40c9-b318-22693d94d2b5)
-Telecom Covarage 
![Telecom Covarage LV](https://github.com/Jimmyokok/LandValueOverhaul/assets/165592666/303a176e-c411-42df-ac1f-76363fffe553)

Without the mod 
-Natural Resourses
![Natural Resourses](https://github.com/Jimmyokok/LandValueOverhaul/assets/165592666/de837a5b-ff2d-4e16-8997-c844dd654f94)
-Telecom Covarage 
![Telecom Covarage](https://github.com/Jimmyokok/LandValueOverhaul/assets/165592666/5d220e09-7082-4288-b27d-6f5783bfaf05)

**Comment by Jimmyokok** [comment]
I just created a new playset to test these info views, and immediately found the building upkeep being not correctly loaded.

**Comment by Jimmyokok** [comment]
And if I change its load order to before all downloaded save games, it immediately worked.

**Comment by SimBoRRis** [comment]
> Did you updated the mod, or did pdx finally loaded as it should? I loaded up a game now, some old city with a lot High Rent issues, they all disappeared in a min. Unfortunately in info those info panels, there is still no color on the ground.

I loaded the same city, this time hing rent stayed. 
![20240403033530_1](https://github.com/Jimmyokok/LandValueOverhaul/assets/165592666/24beca6a-fd60-46b2-bf71-43e739c84d78)

I guess it's a problem with PDX mods, or load order.

**Comment by Jimmyokok** [comment]
No, I'm currently working on the info view issue. It is easy to solve but so hard to make PDXMods correctly load LVO in WIP.

**Comment by Jimmyokok** [comment]
> > Did you updated the mod, or did pdx finally loaded as it should? I loaded up a game now, some old city with a lot High Rent issues, they all disappeared in a min. Unfortunately in info those info panels, there is still no color on the ground.
> 
> I loaded the same city, this time high rent stayed. ![20240403033530_1](https://private-user-images.githubusercontent.com/165592666/319005253-24beca6a-fd60-46b2-bf71-43e739c84d78.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxMDkwODQsIm5iZiI6MTcxMjEwODc4NCwicGF0aCI6Ii8xNjU1OTI2NjYvMzE5MDA1MjUzLTI0YmVjYTZhLWZkNjAtNDZiMi1iZjcxLTQzZTczOWM4NGQ3OC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwM1QwMTQ2MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOWQ0NDJkOGU0MGUzZmEwNWE5OGM4NDQ4NWZkNGI4NzAzY2M5NDA4OGYzMjJkN2JkYWEyY2M3NTcyODE5ZmM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.h2-YlYZhnt-Lpt3BsgT3xmX3pi_S2aK9gPkgjbmn-GE)
> 
> I guess it's a problem with PDX mods, or load order. Just need to restart a game couple of times until LVO starts working correctly.

The low-density upkeep should be around 16 or something similar. If not, LVO is not correctly loaded.

**Comment by Jimmyokok** [comment]
If I totally remove everything related to PDXMods (removing .cache and .pdxsdk folders under ), never log in your PDX account in-game, and install the mod by copying mod content to $user_directory$\AppData\LocalLow\Colossal Order\Cities Skylines II\Mods. The mod is guaranteed to be correctly loaded.

**Comment by SimBoRRis** [comment]
> If I totally remove everything related to PDXMods (removing .cache and .pdxsdk folders under ), never log in your PDX account in-game, and install the mod by copying mod content to userdirectory\AppData\LocalLow\Colossal Order\Cities Skylines II\Mods. The mod is guaranteed to be correctly loaded.

I tried to restart a game 3 times in the row and it loaded LVO no problem.  Maybe it was just luck. I guess this is a solution for now, I will install it manually as you said, this is most important mod for me, can't play without it. 

Since I'm a complete noob when it comes to coding, I just have one more question
Is it possible to implement  a config file for building upgrade coasts, like you did for update distance and spread factor?
I saw that a lot of people are complaining that buildings are leveling up too fast, but I actually liked that.

**Comment by Jimmyokok** [comment]
I have already promoted the modded building upgrade cost in 1.5.0. But yes, making building upgrade cost configurable is an option.

**Comment by SimBoRRis** [comment]
> I have already promoted the modded building upgrade cost in 1.5.0. But yes, making building upgrade cost configurable is an option.

That would be great, I really liked it before, much quicker upgrade. 
Thank you for your help, and for creating this mod. Looking forward for the future updates.

**Comment by KyleWullschleger** [comment]
Same issue - low residential is still saying high rent - and abandoning.

Are these the expected startup mods?  It looks like it's on though.  But I don't see anything about changing land value in the logs.

I've cleared out everything in appData except save games.
I've put LandValueOverhaul mod first in the load order.
Is there anything else I can try other than removing all of PDX mods?

```
[2024-04-02 22:18:37,583] [INFO]  OnLoad
[2024-04-02 22:18:37,585] [INFO]  applying annotated Harmony patches for Jimmyok.LandValueOverhaul
[2024-04-02 22:18:37,647] [INFO]  patching complete
[2024-04-02 22:18:37,650] [INFO]  Patched 7 methods.
[2024-04-02 22:18:37,650] [INFO]  Patched method: Game.dll:GetLevelingCost
[2024-04-02 22:18:37,650] [INFO]  Patched method: Game.dll:OnCreate
[2024-04-02 22:18:37,651] [INFO]  Patched method: Game.dll:OnCreateForCompiler
[2024-04-02 22:18:37,651] [INFO]  Patched method: Game.dll:OnUpdate
[2024-04-02 22:18:37,651] [INFO]  Patched method: Game.dll:AddReader
[2024-04-02 22:18:37,651] [INFO]  Patched method: Game.dll:GetData
[2024-04-02 22:18:37,651] [INFO]  Patched method: Game.dll:GetMap
[2024-04-02 22:18:37,652] [INFO]  Current mod asset at C:/Users/kylew/AppData/LocalLow/Colossal Order/Cities Skylines II/.cache/Mods/mods_subscribed/77397_2/LandValueOverhaul.dll
[2024-04-02 22:18:37,653] [INFO]  Modded LandValueSystem created!
[2024-04-02 22:18:37,658] [INFO]  Modded PropertyRenterSystem created!
[2024-04-02 22:18:37,659] [INFO]  Modded RentAdjustSystem created!
[2024-04-02 22:18:37,660] [INFO]  Modded BuildingUpkeepSystem created!
[2024-04-02 22:18:37,661] [INFO]  Modded LandValueTooltipSystem created!
```

**Comment by Jimmyokok** [comment]
> Same issue - low residential is still saying high rent - and abandoning.
> 
> Are these the expected startup mods? It looks like it's on though. But I don't see anything about changing land value in the logs.
> 
> I've cleared out everything in appData except save games. I've put LandValueOverhaul mod first in the load order. Is there anything else I can try other than removing all of PDX mods?
> 
> ```
> [2024-04-02 22:18:37,583] [INFO]  OnLoad
> [2024-04-02 22:18:37,585] [INFO]  applying annotated Harmony patches for Jimmyok.LandValueOverhaul
> [2024-04-02 22:18:37,647] [INFO]  patching complete
> [2024-04-02 22:18:37,650] [INFO]  Patched 7 methods.
> [2024-04-02 22:18:37,650] [INFO]  Patched method: Game.dll:GetLevelingCost
> [2024-04-02 22:18:37,650] [INFO]  Patched method: Game.dll:OnCreate
> [2024-04-02 22:18:37,651] [INFO]  Patched method: Game.dll:OnCreateForCompiler
> [2024-04-02 22:18:37,651] [INFO]  Patched method: Game.dll:OnUpdate
> [2024-04-02 22:18:37,651] [INFO]  Patched method: Game.dll:AddReader
> [2024-04-02 22:18:37,651] [INFO]  Patched method: Game.dll:GetData
> [2024-04-02 22:18:37,651] [INFO]  Patched method: Game.dll:GetMap
> [2024-04-02 22:18:37,652] [INFO]  Current mod asset at C:/Users/kylew/AppData/LocalLow/Colossal Order/Cities Skylines II/.cache/Mods/mods_subscribed/77397_2/LandValueOverhaul.dll
> [2024-04-02 22:18:37,653] [INFO]  Modded LandValueSystem created!
> [2024-04-02 22:18:37,658] [INFO]  Modded PropertyRenterSystem created!
> [2024-04-02 22:18:37,659] [INFO]  Modded RentAdjustSystem created!
> [2024-04-02 22:18:37,660] [INFO]  Modded BuildingUpkeepSystem created!
> [2024-04-02 22:18:37,661] [INFO]  Modded LandValueTooltipSystem created!
> ```

There should be something like "Building upkeep modified!". In case your log does not contain this line, LVO is not correctly loaded, causing unusually high building upkeep, leading to high rent.

**Comment by Jimmyokok** [comment]
Update 1.5.1 fixed the info view system. The building upgrade cost remains not configurable for now, because the building upgrade cost should be something properly configured before starting a new save and remains static throughout the entire game.
