### ISSUE TITLE
Land Value Spike

### ISSUE THREAD

**Issue by SimBoRRis** [Jimmyokok/LandValueOverhaul#16]
I don't know can this help you in any way, after playing for more then 6 hours I got extremely high land value in odd places.

As you can se in the pic below:
![Close up](https://github.com/Jimmyokok/LandValueOverhaul/assets/165592666/5cd9dce3-cdf1-4ffc-802b-02d198957ae6)

It started spreading from the corners

![Close up 2](https://github.com/Jimmyokok/LandValueOverhaul/assets/165592666/4738955d-c9a9-44af-be13-7483aa5d59d3)

This is the view of the whole city, with a downtown which is far away from this high land value

![Whole Map](https://github.com/Jimmyokok/LandValueOverhaul/assets/165592666/9ddbbbcd-b8d3-40cd-ad9f-1f682660bcc4)

And then again closer look to the source, even tho, there is nothing there that can affect land value to these extremes

![Circle no info](https://github.com/Jimmyokok/LandValueOverhaul/assets/165592666/84f51258-e90a-444d-8f36-407b52e991e3)
![Circle info](https://github.com/Jimmyokok/LandValueOverhaul/assets/165592666/2d9091fa-7fe3-4c6d-a48b-085a764a9fef)

![Corner no info](https://github.com/Jimmyokok/LandValueOverhaul/assets/165592666/7043ded1-7113-46ed-96c8-52ec1f4c4361)
![Corner info](https://github.com/Jimmyokok/LandValueOverhaul/assets/165592666/013e3e14-fc33-4c90-a83d-bba08ac3ec3f)

**Comment by Jimmyokok** [comment]
Could you please share your save? I will try to find its root cause.

**Comment by SimBoRRis** [comment]
Yes of course, just so you know, when I started a city I did not have LV mod, so it's not a fresh start with your mod>
I also have other mods enabled:
I18n EveryWhere
Unified Icon Library
DependencyPack
ExtraLib
Gooee
Achievement Enabler
Anarchy
Better Bulldozer
Move It
Line Tool
Tree Controller
Water Features
School Capacity Balancer
Plop the Growables
Magical Hearse
ZoningToolkit
Image Overlay
ExtraLandscapingTools
Extended Road Upgrades
Cim Route Highlighter (Formerly Employee Tracker)
AutoDistrictNameStations
Extra Networks and Areas
UltimateMonitor
FirstPersonCamera
ExtendedTooltip

My Save Game:

https://we.tl/t-KCYxikuy17

**Comment by Jimmyokok** [comment]
I loaded your save with only LVO enabled, and the LV at those regions immediately begins to plummet, falling at > 200$ per second...

**Comment by Jimmyokok** [comment]
Have you checked if the building upkeep modification has been correctly loaded?

**Comment by SimBoRRis** [comment]
> Have you checked if the building upkeep modification has been correctly loaded?

Yes, mod was working prefect today.
I will check tomorrow which mod is causing this spike, but defiantly it's not LVO.

**Comment by Jimmyokok** [comment]
It is a bug, causing LV sometimes being regarded as 0 when computing current rent. Will update soon.

**Comment by Jimmyokok** [comment]
Typically, places where there is no healthcare coverage will be affected.

**Comment by SimBoRRis** [comment]
Hi, another spike 
Next to High Residential Signature buildings in the middle of nowhere.
When I bulldoze them it starts to drop.
![20240405224248_1](https://github.com/Jimmyokok/LandValueOverhaul/assets/165592666/69687512-447b-4895-9ea2-9054ceaf4310)
![20240405224238_1](https://github.com/Jimmyokok/LandValueOverhaul/assets/165592666/3596718a-812a-4d6f-9886-0b61fc4230de)
