### ISSUE TITLE
Newest version cause tons of error when using with other mods

### ISSUE THREAD

**Issue by GIS-PuppetMaster** [Jimmyokok/LandValueOverhaul#17]
Here is the log file, after I uninstalled this mod, all those errors disappeared.
https://discord.com/channels/1169011184557637825/1207641575362920508/1225475411337805834

**Comment by GIS-PuppetMaster** [comment]
如果你打不开那个链接的话通过这个邀请链接进入https://discord.gg/4ev4j6C8

**Comment by Jimmyokok** [comment]
成功注册了第五个discord账号，希望不要再被光速封号。

**Comment by Jimmyokok** [comment]
本mod还没有适配BepInEx，强行加载不知道会发生什么。同时，你的log里报错的是realeco和findstuff，我将LVO删除后，它们仍然报错。

**Comment by GIS-PuppetMaster** [comment]
> 本mod还没有适配BepInEx，强行加载不知道会发生什么。同时，你的log里报错的是realeco和findstuff，我将LVO删除后，它们仍然报错。

Realeco的第一个报错好像是他自己的问题？不过我这边删除lvo之后就没有报错了。lvo回滚到1.5.1的话只有realeco的报错。你确定删除了么，有时候得进游戏同步之后重启游戏才能生效

**Comment by GIS-PuppetMaster** [comment]
bepinex是红绿灯mod的依赖项，我用pdxmod和thunder store一起加载的，一会我试试关了thunder store

**Comment by Jimmyokok** [comment]
我测试的时候全部都是手动安装mod，且游戏中不登录p社账号，也不点进PDXMods，肯定是正确加载了。
LVO更新1.5.4了，之前版本游戏system的加载有点问题，1.5.4修复了这个问题（但是仍然不能解释为什么1.5.3和1.5.1会呈现出区别，这两个版本的区别仅仅是数值）

**Comment by Jimmyokok** [comment]
我直接使用PMOD管理mod，并使用以下playset，在LVO 1.5.4下没有任何报错
![image](https://github.com/Jimmyokok/LandValueOverhaul/assets/55531280/aaa31e35-87b0-4012-bf66-81fd06536ec0)
[Modding.log](https://github.com/Jimmyokok/LandValueOverhaul/files/14879288/Modding.log)
虽然在游戏中一些建筑的维护费被RealEco覆盖了，但是并没有致命问题。

**Comment by GIS-PuppetMaster** [comment]
> 我直接使用PMOD管理mod，并使用以下playset，在LVO 1.5.4下没有任何报错 ![image](https://private-user-images.githubusercontent.com/55531280/319843152-aaa31e35-87b0-4012-bf66-81fd06536ec0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyOTkxMjQsIm5iZiI6MTcxMjI5ODgyNCwicGF0aCI6Ii81NTUzMTI4MC8zMTk4NDMxNTItYWFhMzFlMzUtODdiMC00MDEyLWJmNjYtODFmZDA2NTM2ZWMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA1VDA2MzM0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyYzdhZTU0MTdjOTIzM2I3YjAwOTU2MjVkZWE3ZWQwZTdhZTgzYTY0MmJlNGVmYmYwNjZlZjcyZTRiNjRhYWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nmgH5RqI6AIRxUSj9ezEanZ8aAyX7qsoBRSD6zSfmCw) [Modding.log](https://github.com/Jimmyokok/LandValueOverhaul/files/14879288/Modding.log) 虽然在游戏中一些建筑的维护费被RealEco覆盖了，但是并没有致命问题。

刚才又自动更新了一堆mod，这次奇迹般地没错误了，可能之前是LVO和其他某个mod冲突了？总之现在问题解决了
