### ISSUE TITLE
Residential demand non-existent since 1.1.0f1

### ISSUE THREAD

**Issue by oeed** [Jimmyokok/LandValueOverhaul#18]
Thank you so much for this mod, it's truly impossible to play without.

My city was working well with your pre-1.1.0f1 version of the mod, healthy (but balanced) population growth. When 1.1.0f1 was released and the mod was briefly unsupported all my low density complained about high rent and my population declined. I stopped playing for a week or so until I noticed you'd added it to Paradox Mods so I thought I'd give it ago.

After playing and leaving it running for a number of hours most of the high rent complaints disappeared, but I seem to have negative residential demand now. My population's dropped from 144,000 to just over 100,000. Tons of buildings have been abandoned, many apartments are half empty, etc. In the demand screen low density is complaining about "cost of living", which I assume means land value being too high. In low density area, land value is generally white and between $17,000 and $22,000 (not sure if that's low or high).

I cannot for the life of me figure out how to stop this population loss spiral, so any suggestions are welcome! Happy to share the save or any other helpful data.

![20240406223447_1](https://github.com/Jimmyokok/LandValueOverhaul/assets/3835991/236081c4-5b2b-4ca0-b582-e8caef871c73)

![20240406223620_1](https://github.com/Jimmyokok/LandValueOverhaul/assets/3835991/9cbcc970-a99e-4196-88d2-16e28785b54e)

![20240406223502_1](https://github.com/Jimmyokok/LandValueOverhaul/assets/3835991/edf9a6c9-8b7d-4bfa-adf5-13844a7e9c73)

**Comment by Jimmyokok** [comment]
I need your save and mod list. 
When I was testing the mod in my test city, which has a population of 110,000, the population rose to around 156,000 after running the city for several hours.

**Comment by oeed** [comment]
Save: https://drive.google.com/file/d/1mdcSzc0RwQs13Xtk-LlE3muNdhYSVX7Z/view?usp=sharing

Mod list:
- Move It
- Unified Icon Library
- Anarchy
- Line Tool
- School Capacity Balancer
- Realistic Building Occupancy
- Extra Networks and Areas
- Land Value Overhaul
- DependencyPack
- Gooee

For some reason commerical demand is always really high too. I tried to see if creating more jobs would help, but if I zone large amounts of commercial and office they all then complain about no customers, low density residential land value sky increases and high rent bubble appear again.

**Comment by Jimmyokok** [comment]
Via the InfoLoom mod, I found the following:

![image](https://github.com/Jimmyokok/LandValueOverhaul/assets/55531280/25b21dfa-79ec-4dd5-8a62-21af6c2a5e8c)

Your low residential demand is 100% caused by empty properties, whose cause I'm actively investigating.

**Comment by SimBoRRis** [comment]
I think, High cost of living is tie to number of homeless people you have in the city. Maybe and just maybe your problem has more to do with Realistic Building Occupancy then Land Value Overhaul mod. I know that that mod has some problems if you didn't start a city with it. Have you tried removing it, and letting game run for a while?

**Comment by oeed** [comment]
It did indeed seem to be more of an issue with Realistic Building Occupancy. That said, I still have issues with high rent, but that's a different issue.
