### ISSUE TITLE
Missing road required icon when placing most service buildings

### ISSUE THREAD

**Issue by Haneybd87** [Jimmyokok/LandValueOverhaul#4]
When placing service buildings with snapping off, it doesn't matter how far back it is from the road, no "road required" icon pops up with this mod installed. This happens with most, but not all service buildings. I've narrowed it down to this mod and this mod alone doing it.

**Comment by Jimmyokok** [comment]
Bug confirmed. It will be fixed very quickly.

**Comment by Jimmyokok** [comment]
A small update (1.4.1) has been made to fix this bug.
