### ISSUE TITLE
Big truck (semi trucks, oil trucks, etc) residential deliveries

### ISSUE THREAD

**Issue by ChristopherJohnBrennan** [Jimmyokok/LandValueOverhaul#8]
Hi!  Thanks for working on this mod!

I wanted to provide some info I'm hoping you'll find useful.

I installed the mod for the first time yesterday (only it and the required BepInEx-BepInExPack) on 1.0.19f1.  

I had never seen big trucks (semi trucks, oil trucks, etc) making any residential deliveries before I installed it. Now I've got the big trucks making deliveries to all my houses just after they get built and when they level up.

It happens in small new cities, and it happens with a full-on truck invasion when you load an larger existing city for the first time with the mod installed because you get a lot of levelling up all at once.

Here's a current reddit thread on it: 
https://www.reddit.com/r/CitiesSkylines2/comments/1apyuwn/has_anyone_run_into_this_bug_before_less_than/

Here's another thread from the end of December:
https://www.reddit.com/r/CitiesSkylines/comments/18so3xv/why_are_all_these_empty_industrial_trucks/

Thanks again.

**Comment by Jimmyokok** [comment]
Could you provide your save? Especially the one before you installed this mod and ran into the delivery truck disaster.

**Comment by ChristopherJohnBrennan** [comment]
I'm sorry but it's been overwritten.  I'll build up a new one and then give you the pre- and post- mod versions.

**Comment by Jimmyokok** [comment]
I have located the problem. It turns out to be **yeeeeeeeeeet another** numerically unstable piece of code from vanilla, resulting in the frequency of material upkeep delivery being inversely proportional to the absolute value of the building upkeep.
I small update (1.4.3) has been made to fix this vanilla flaw.

**Comment by ChristopherJohnBrennan** [comment]
Awesome.  I'll give it shot.  Thanks!

**Comment by ChristopherJohnBrennan** [comment]
And just wanted you to know that it looks like the mod is working when I look at the land value map.  And happily there are no more big truck invasions.  Thanks!
