### ISSUE TITLE
version 1.4.3 crash the game sometimes

### ISSUE THREAD

**Issue by GIS-PuppetMaster** [Jimmyokok/LandValueOverhaul#9]
I just updated this mod, and before updating, I can play my save for more than 72 hours without crashing. After I updated it, the game crashed very frequently, couldn't play it for more than 30 minutes. My save has 350K population.

**Comment by Jimmyokok** [comment]
Currently I have no time to deal with this, and it would be better if you could provide your game error log and your mod list. And also, the recent mod update has no impact on your city, given that your city is already a massive one. While I'm still working on this crashing issue, I recommend you to temporaily switch back to 1.4.2.

**Comment by GIS-PuppetMaster** [comment]
> Currently I have no time to deal with this, and it would be better if you could provide your game error log and your mod list. And also, the recent mod update has no impact on your city, given that your city is already a massive one. While I'm still working on this crashing issue, I recommend you to temporaily switch back to 1.4.2.目前我没有时间处理这个问题，如果你能提供你的游戏错误日志和你的模组列表会更好。而且，最近的模组更新对你的城市没有影响，因为你的城市已经是一个巨大的城市。虽然我仍在处理这个崩溃的问题，但我建议您暂时切换回 1.4.2。

I have checked all logs, no useful information in it, I'll post everything you need later

**Comment by Jimmyokok** [comment]
似乎与其他mod无关。
我有一个猜想，但是首先需要复现闪退，才能验证问题。
